### ISSUE TITLE
kwplayer crashed with AttributeError in on_main_menu_pref_activate()

### ISSUE THREAD

**Issue by bladesilent** [LiuLang/kwplayer-packages#62]
版本：kwplayer_3.4.9-3_all.deb
操作系统：Ubuntu 14.04 LTS

重现步骤：
1, 打开kwplayer
2, 打开“preference”窗口
3, 从左到右依次点击所有tab
4, 关闭“preference”窗口
5, 系统提示kwplayer已崩溃，但是kwplayer还是可以用的，估计是preference窗口崩溃，不熟悉python所以在此汇报bug。

crash摘要（/var/crash/_usr_bin_kwplayer.****.crash）

ProblemType: Crash
CurrentDesktop: Unity
Date: Sun Jan  4 22:57:54 2015
ExecutablePath: /usr/bin/kwplayer
ExecutableTimestamp: 1420164264
InterpreterPath: /usr/bin/python3.4
ProcCmdline: /usr/bin/python3 /usr/bin/kwplayer
ProcCwd: /home/luchsh
ProcEnviron:
 LANGUAGE=en_US
 LC_TIME=zh_CN.UTF-8
 LC_MONETARY=zh_CN.UTF-8
 PATH=(custom, no user)
 XDG_RUNTIME_DIR=<set>
 LC_ADDRESS=zh_CN.UTF-8
 LANG=en_US.UTF-8
 LC_TELEPHONE=zh_CN.UTF-8
 SHELL=/bin/bash
 LC_NAME=zh_CN.UTF-8
 LC_MEASUREMENT=zh_CN.UTF-8
 LC_IDENTIFICATION=zh_CN.UTF-8
 LC_NUMERIC=zh_CN.UTF-8
 LC_PAPER=zh_CN.UTF-8
ProcMaps:
 00400000-00754000 r-xp 00000000 08:17 263132                             /usr/bin/python3.4
 00953000-00954000 r--p 00353000 08:17 263132                             /usr/bin/python3.4
........................................
ProcStatus:
 Name:	kwplayer
 State:	R (running)
 Tgid:	6951
 Ngid:	0
 Pid:	6951
 PPid:	1711
 TracerPid:	0
 Uid:	1000	1000	1000	1000
 Gid:	1000	1000	1000	1000
 FDSize:	64
 Groups:	4 24 27 30 46 108 124 1000 
 VmPeak:	  747076 kB
 VmSize:	  724760 kB
 VmLck:	       0 kB
 VmPin:	       0 kB
 VmHWM:	   68968 kB
 VmRSS:	   68216 kB
 VmData:	  324892 kB
 VmStk:	     136 kB
 VmExe:	    3408 kB
 VmLib:	   31660 kB
 VmPTE:	     768 kB
 VmSwap:	       0 kB
 Threads:	3
 SigQ:	0/127841
 SigPnd:	0000000000000000
 ShdPnd:	0000000000000000
 SigBlk:	0000000000000000
 SigIgn:	0000000001001000
 SigCgt:	0000000180000002
 CapInh:	0000000000000000
 CapPrm:	0000000000000000
 CapEff:	0000000000000000
 CapBnd:	0000001fffffffff
 Seccomp:	0
 Cpus_allowed:	f
 Cpus_allowed_list:	0-3
 Mems_allowed:	00000000,00000001
 Mems_allowed_list:	0
 voluntary_ctxt_switches:	2684
 nonvoluntary_ctxt_switches:	929
PythonArgs: ['/usr/bin/kwplayer']
Traceback:
 Traceback (most recent call last):
   File "/usr/lib/python3/dist-packages/kuwo/Player.py", line 685, in on_main_menu_pref_activate
     self.app.reset_notebook_tabs()
 AttributeError: 'App' object has no attribute 'reset_notebook_tabs'
UserGroups: adm cdrom dip lpadmin plugdev sambashare sudo
_LogindSession: /user/1000.user/c2.session
ApportVersion: 2.14.1-0ubuntu3.6
Architecture: amd64
Dependencies:
 acl 2.2.52-1
 adduser 3.113+nmu3ubuntu3
 apt-utils 1.0.1ubuntu2.6
 at-spi2-core 2.10.2.is.2.10.1-0ubuntu1
 base-passwd 3.5.33
........................................
 zlib1g 1:1.2.8.dfsg-1ubuntu1
DistroRelease: Ubuntu 14.04
InstallationDate: Installed on 2015-01-04 (0 days ago)
InstallationMedia: Ubuntu 14.04.1 LTS "Trusty Tahr" - Release amd64 (20140722.2)
NonfreeKernelModules: nvidia
Package: kwplayer 3.4.9-3 [origin: unknown]
PackageArchitecture: all
ProcVersionSignature: Ubuntu 3.13.0-43.72-generic 3.13.11.11
SourcePackage: kwplayer
Tags: third-party-packages trusty
Title: kwplayer crashed with AttributeError in on_main_menu_pref_activate(): 'App' object has no attribute 'reset_notebook_tabs'
Uname: Linux 3.13.0-43-generic x86_64
UnreportableReason: This is not an official Ubuntu package. Please remove any third party package and try again.
UpgradeStatus: No upgrade log present (probably fresh install)
_MarkForUpload: True

**Comment by LiuLang** [comment]
这个是上个版本遗留下来的错误, 已经修复.
谢谢反馈

**Comment by bladesilent** [comment]
确认修掉了，谢谢！
