### ISSUE TITLE
Debian jessie 依赖问题

### ISSUE THREAD

**Issue by re2953** [LiuLang/kwplayer-packages#63]
我的debian jessie下缺少 gir1.2-gtk-3.0  gstreamer1.0-alsa  python3-mutagen，可能还有其他依赖

1，没有gir1.2-gtk-3.0会使用2.0库，但是无法启动
2，缺少gstreamer1.0-alsa，正常运行，有图像，但是没声音，也不会报错
3，在log中提示缺少python3-mutagen

软件不错，好用。

**Comment by LiuLang** [comment]
1.如果没有gir1.2-gtk-3.0, 就不能调用gtk3来绘制界面. 当然, 跟gtk2.0没有任何关系.
2.gstreamer1.0-alsa, 这个库不是必须的, 除非你的声音系统是ALSA, 而不是默认的PulseAudio. 而现在看来, 主流的发行版都是默认使用PulseAudio的, 所以就没有写进去.
3. python3-mutagen这个包在软件库里面是有的, 缺少它的话, 就可能自动转换mp3文件里的编码(从gtk转为utf8).

**Comment by re2953** [comment]
1，我的意思是会用gir1.2-gtk-2.0
2，alsa必有，pulse可有可无
3，这个是你的程序log里面的ERROR提示，具体我不了解，

**Comment by LiuLang** [comment]
嘿嘿, 估计你有些误会我说话的语气了 ;-)
gir1.2-gtk-2.0是gtk2.0的GIR接口绑定, 而kwplayer用的是gtk3.0, 所以没有必要安装这个包.
ALSA的话, 渐渐会退出的, 被PulseAudio替代. 如果你系统里没有用到PulseAudio, 只需要安装那个gstreamer包就可以了. 这个的话, 我会在README里面说明一下的, 以免其它人有遇到的类似问题.
mutagenx 是可选包.

**Comment by re2953** [comment]
看来我没说明白，是这样的
1，kwplayer依赖不会自动安装gir1.2-gtk-3.0，我的系统默认使用gir1.2-gtk-2.0。
2，但是kwplayer当然不是用gir1.2-gtk-2.0，因此会出错，需要手动安装gir1.2-gtk-3.0。
3，alsa还是pulseaudio谁好，对我不重要，我也不关心，但是我的系统是用alsa。在这种系统软件配置下，因为只有alsa，所以需要手动安装gstreamer1.0-alsa。

虽然我编程菜，但是各个包是干什么用的我还是知道的。

**Comment by LiuLang** [comment]
On 01/14/2015 10:06 AM, re2953 wrote:
> 看来我没说明白，是这样的
> 1，kwplayer依赖不会自动安装gir1.2-gtk-3.0，我的系统默认使用gir1.2-gtk-2.0。
> 2，但是kwplayer当然不是用gir1.2-gtk-2.0，因此会出错，需要手动安装gir1.2-gtk-3.0。
> 3，alsa还是pulseaudio谁好，对我不重要，我也不关心，但是我的系统是用alsa。在这种系统软件配置下，因为只有alsa，所以需要手动安装gstreamer1.0-alsa。
>
> 虽然我编程菜，但是各个包是干什么用的我还是知道的。
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/LiuLang/kwplayer-packages/issues/63#issuecomment-69857974
>
你要说的是: 你自己安装了一个很轻量级的桌面环境, 里面几乎没有gtk的多少东 
西, 然后kwplayer的安装包里面缺少了一些依赖, 至使程序跑不起来?
那你装上就是了. gir1.2-gtk-3.0这个包我会加入到包依赖列表里的, alsa那个不会.

谢谢你的反馈 ;-)
