### ISSUE TITLE
archlinux的3.4.9还没更新呢？

### ISSUE THREAD

**Issue by behind1231** [LiuLang/kwplayer-packages#64]
作者，我一直有帮打包的，还放到ARCHLINUX的AUR上，最近为什么还没出3.4.9的呢？

**Comment by LiuLang** [comment]
哪个?
如果直接放到了AUR, 就不需要再复制一份到这里了, 直接在README里面说明就行.

**Comment by behind1231** [comment]
https://pypi.python.org/packages/source/k/kwplayer/
看这里的，还是3。4。8，3。4。9没更新我更新不了啊～！

**Comment by behind1231** [comment]
https://pypi.python.org/packages/source/k/kwplayer/
看这里的，还是3。4。8，3。4。9没更新我更新不了啊～！

**Comment by LiuLang** [comment]
On 01/14/2015 03:52 PM, behind1231 wrote:
> https://pypi.python.org/packages/source/k/kwplayer/
> 看这里的，还是3。4。8，3。4。9没更新我更新不了啊～！
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/LiuLang/kwplayer-packages/issues/64#issuecomment-69880401
>
忘了推送过去了 ;-)
已更新

**Comment by behind1231** [comment]
好的，我更新一下～！

**Comment by behind1231** [comment]
已更新了，不过我想知道更新了那些东西？？？

**Comment by LiuLang** [comment]
https://github.com/LiuLang/kwplayer/blob/master/HISTORY

**Comment by behind1231** [comment]
作者，今天发现这里上不了https://pypi.python.org/packages/source/b/bcloud！是怎么回事？以后如何打包啊。

**Comment by LiuLang** [comment]
后来是要写明版本号的, 比如: https://pypi.python.org/packages/source/b/bcloud/bcloud-3.6.1.tar.gz#md5=38c9f58d2a4f31c99b66ad159e164ab5

**Comment by behind1231** [comment]
不对，作者我的意思是，我以后看不到更新到那个版本，这网站上不了我也不知道有没有更新，你明白我意思吧～！
